### ISSUE TITLE
Fix layout of Training Courses page

### ISSUE THREAD

**Issue by gubuntu** [kartoza/docker-mezzanine#113]
remove huge white space

Products near the bottom are not arranged properly.

**Comment by cchristelis** [comment]
fixed by #128

**Comment by gubuntu** [comment]
if this is fixed it's not deployed. All these fixes should have gone into 1.0.0?

**Comment by ismailsunni** [comment]
The layout is still not in proper one.
![selection_003](https://cloud.githubusercontent.com/assets/1421861/18654501/b8f4517a-7f0b-11e6-82ad-6b8246fc3d49.png)

**Comment by dimasciput** [comment]
Hi @ismailsunni , could you tell me what is the proper one? 
This is actually is in my PR : https://github.com/kartoza/docker-mezzanine/issues/128

**Comment by ismailsunni** [comment]
Hi @dimasciput 
I thought the black layer in front of the logo is not intentional. For me, I feel something wrong. Perhaps we can make the black layer not in one piece.

**Comment by gubuntu** [comment]
I think this is actually correct but the black layer also doesn't do it for me. Perhaps change to a very light touch of transparent grey?

**Comment by timlinux** [comment]
Yes its damn ugly. I prefer we put the title underneath the logo rather than as an overlay. Then we can use solid colours (use one of the kartoza logo colours) for the box and white text on top.
